version: "3.9"
services:
  proyecto1:
    image: 'proyecto1:1'
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/proyecto1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
  db:
    image: 'postgres:latest'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=proyecto1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - proyecto1:/var/lib/postgresql/data

volumes:
  proyecto1: